# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/cameron.foltz/recOrder/recOrder/plugin/qtdesigner/recOrder_calibration_06232021.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(512, 966)
        self.cb_calibration_mode = QtWidgets.QComboBox(Form)
        self.cb_calibration_mode.setGeometry(QtCore.QRect(160, 185, 187, 31))
        self.cb_calibration_mode.setObjectName("cb_calibration_mode")
        self.cb_calibration_mode.addItem("")
        self.cb_calibration_mode.addItem("")
        self.cb_calibration_mode.addItem("")
        self.qbutton_calibrate_lc = QtWidgets.QPushButton(Form)
        self.qbutton_calibrate_lc.setGeometry(QtCore.QRect(0, 300, 311, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qbutton_calibrate_lc.sizePolicy().hasHeightForWidth())
        self.qbutton_calibrate_lc.setSizePolicy(sizePolicy)
        self.qbutton_calibrate_lc.setAutoDefault(False)
        self.qbutton_calibrate_lc.setObjectName("qbutton_calibrate_lc")
        self.le_swing = QtWidgets.QLineEdit(Form)
        self.le_swing.setGeometry(QtCore.QRect(160, 130, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_swing.sizePolicy().hasHeightForWidth())
        self.le_swing.setSizePolicy(sizePolicy)
        self.le_swing.setObjectName("le_swing")
        self.le_extinction = QtWidgets.QLineEdit(Form)
        self.le_extinction.setGeometry(QtCore.QRect(80, 440, 221, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_extinction.sizePolicy().hasHeightForWidth())
        self.le_extinction.setSizePolicy(sizePolicy)
        self.le_extinction.setReadOnly(True)
        self.le_extinction.setObjectName("le_extinction")
        self.label_wavelength = QtWidgets.QLabel(Form)
        self.label_wavelength.setGeometry(QtCore.QRect(10, 160, 91, 21))
        self.label_wavelength.setObjectName("label_wavelength")
        self.label_swing = QtWidgets.QLabel(Form)
        self.label_swing.setGeometry(QtCore.QRect(10, 130, 73, 21))
        self.label_swing.setObjectName("label_swing")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(-20, 280, 761, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_extinction = QtWidgets.QLabel(Form)
        self.label_extinction.setGeometry(QtCore.QRect(10, 440, 60, 21))
        self.label_extinction.setObjectName("label_extinction")
        self.le_wavelength = QtWidgets.QLineEdit(Form)
        self.le_wavelength.setGeometry(QtCore.QRect(160, 160, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_wavelength.sizePolicy().hasHeightForWidth())
        self.le_wavelength.setSizePolicy(sizePolicy)
        self.le_wavelength.setObjectName("le_wavelength")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(10, 390, 291, 21))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(160, 100, 211, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.line_11 = QtWidgets.QFrame(Form)
        self.line_11.setGeometry(QtCore.QRect(-50, 500, 831, 20))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.label_dir = QtWidgets.QLabel(Form)
        self.label_dir.setGeometry(QtCore.QRect(10, 100, 56, 16))
        self.label_dir.setObjectName("label_dir")
        self.line_12 = QtWidgets.QFrame(Form)
        self.line_12.setGeometry(QtCore.QRect(-10, 80, 771, 20))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(380, 100, 87, 21))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setCheckable(False)
        self.pushButton.setDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.label_progress = QtWidgets.QLabel(Form)
        self.label_progress.setGeometry(QtCore.QRect(130, 370, 60, 16))
        self.label_progress.setObjectName("label_progress")
        self.label_inten_plot = QtWidgets.QLabel(Form)
        self.label_inten_plot.setGeometry(QtCore.QRect(100, 520, 111, 16))
        self.label_inten_plot.setObjectName("label_inten_plot")
        self.plot_window = QtWidgets.QGraphicsView(Form)
        self.plot_window.setGeometry(QtCore.QRect(10, 540, 256, 192))
        self.plot_window.setObjectName("plot_window")
        self.label_scheme = QtWidgets.QLabel(Form)
        self.label_scheme.setGeometry(QtCore.QRect(10, 190, 131, 16))
        self.label_scheme.setObjectName("label_scheme")
        self.label_calibration_params = QtWidgets.QLabel(Form)
        self.label_calibration_params.setGeometry(QtCore.QRect(10, 70, 171, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_calibration_params.setFont(font)
        self.label_calibration_params.setObjectName("label_calibration_params")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(10, 220, 141, 20))
        self.checkBox.setObjectName("checkBox")
        self.label_calibration_params_2 = QtWidgets.QLabel(Form)
        self.label_calibration_params_2.setGeometry(QtCore.QRect(270, 290, 161, 21))
        self.label_calibration_params_2.setText("")
        self.label_calibration_params_2.setObjectName("label_calibration_params_2")
        self.label_inten_plot_2 = QtWidgets.QLabel(Form)
        self.label_inten_plot_2.setGeometry(QtCore.QRect(120, 760, 31, 16))
        self.label_inten_plot_2.setObjectName("label_inten_plot_2")
        self.plot_window_2 = QtWidgets.QGraphicsView(Form)
        self.plot_window_2.setGeometry(QtCore.QRect(10, 780, 256, 131))
        self.plot_window_2.setObjectName("plot_window_2")
        self.label_calibration_params_4 = QtWidgets.QLabel(Form)
        self.label_calibration_params_4.setGeometry(QtCore.QRect(10, 270, 171, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_calibration_params_4.setFont(font)
        self.label_calibration_params_4.setObjectName("label_calibration_params_4")
        self.label_calibration_params_5 = QtWidgets.QLabel(Form)
        self.label_calibration_params_5.setGeometry(QtCore.QRect(10, 490, 171, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_calibration_params_5.setFont(font)
        self.label_calibration_params_5.setObjectName("label_calibration_params_5")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(0, 70, 521, 851))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 519, 849))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.scrollAreaWidgetContents)
        self.verticalScrollBar.setGeometry(QtCore.QRect(490, 9, 20, 831))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea.raise_()
        self.cb_calibration_mode.raise_()
        self.qbutton_calibrate_lc.raise_()
        self.le_swing.raise_()
        self.le_extinction.raise_()
        self.label_wavelength.raise_()
        self.label_swing.raise_()
        self.line.raise_()
        self.label_extinction.raise_()
        self.le_wavelength.raise_()
        self.progressBar.raise_()
        self.lineEdit.raise_()
        self.line_11.raise_()
        self.label_dir.raise_()
        self.line_12.raise_()
        self.pushButton.raise_()
        self.label_progress.raise_()
        self.label_inten_plot.raise_()
        self.plot_window.raise_()
        self.label_scheme.raise_()
        self.label_calibration_params.raise_()
        self.checkBox.raise_()
        self.label_calibration_params_2.raise_()
        self.label_inten_plot_2.raise_()
        self.plot_window_2.raise_()
        self.label_calibration_params_4.raise_()
        self.label_calibration_params_5.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.cb_calibration_mode.setItemText(0, _translate("Form", "Full"))
        self.cb_calibration_mode.setItemText(1, _translate("Form", "Coarse"))
        self.cb_calibration_mode.setItemText(2, _translate("Form", "Fine"))
        self.qbutton_calibrate_lc.setText(_translate("Form", "Calibrate LC"))
        self.le_swing.setText(_translate("Form", "0.03"))
        self.label_wavelength.setText(_translate("Form", "Wavelength"))
        self.label_swing.setText(_translate("Form", "Swing"))
        self.label_extinction.setText(_translate("Form", "Extinction"))
        self.le_wavelength.setText(_translate("Form", "532"))
        self.lineEdit.setText(_translate("Form", "/path/"))
        self.label_dir.setText(_translate("Form", "Directory"))
        self.pushButton.setText(_translate("Form", "Browse"))
        self.label_progress.setText(_translate("Form", "Progress"))
        self.label_inten_plot.setText(_translate("Form", "Intensity Plot"))
        self.label_scheme.setText(_translate("Form", "Illumination Scheme"))
        self.label_calibration_params.setText(_translate("Form", "Calibration Parameters"))
        self.checkBox.setText(_translate("Form", "Use Cropped ROI"))
        self.label_inten_plot_2.setText(_translate("Form", "Log"))
        self.label_calibration_params_4.setText(_translate("Form", "Run Calibration"))
        self.label_calibration_params_5.setText(_translate("Form", "Calibration Feedback"))

