# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/cameron.foltz/recOrder/recOrder/plugin/qtdesigner/recOrder_calibration_scroll_v2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(546, 807)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 783))
        self.scrollArea.setMouseTracking(False)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 432, 781))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.label_calibration_params_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_calibration_params_2.setText("")
        self.label_calibration_params_2.setObjectName("label_calibration_params_2")
        self.gridLayout.addWidget(self.label_calibration_params_2, 7, 4, 1, 2)
        self.le_wavelength = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_wavelength.sizePolicy().hasHeightForWidth())
        self.le_wavelength.setSizePolicy(sizePolicy)
        self.le_wavelength.setObjectName("le_wavelength")
        self.gridLayout.addWidget(self.le_wavelength, 3, 3, 1, 2)
        self.label_scheme = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_scheme.setObjectName("label_scheme")
        self.gridLayout.addWidget(self.label_scheme, 4, 0, 1, 3)
        self.label_calibration_params = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_calibration_params.setFont(font)
        self.label_calibration_params.setObjectName("label_calibration_params")
        self.gridLayout.addWidget(self.label_calibration_params, 0, 0, 1, 4)
        self.qbutton_calibrate_lc = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qbutton_calibrate_lc.sizePolicy().hasHeightForWidth())
        self.qbutton_calibrate_lc.setSizePolicy(sizePolicy)
        self.qbutton_calibrate_lc.setAutoDefault(False)
        self.qbutton_calibrate_lc.setObjectName("qbutton_calibrate_lc")
        self.gridLayout.addWidget(self.qbutton_calibrate_lc, 7, 0, 2, 5)
        self.label_calibration_params_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_calibration_params_5.setFont(font)
        self.label_calibration_params_5.setObjectName("label_calibration_params_5")
        self.gridLayout.addWidget(self.label_calibration_params_5, 12, 0, 1, 4)
        self.label_swing = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_swing.setObjectName("label_swing")
        self.gridLayout.addWidget(self.label_swing, 2, 0, 1, 2)
        self.plot_window = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.plot_window.setObjectName("plot_window")
        self.gridLayout.addWidget(self.plot_window, 15, 0, 1, 4)
        self.plot_window_2 = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.plot_window_2.setObjectName("plot_window_2")
        self.gridLayout.addWidget(self.plot_window_2, 17, 0, 1, 4)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setCheckable(False)
        self.pushButton.setDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 5, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 3, 1, 2)
        self.label_extinction = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_extinction.setObjectName("label_extinction")
        self.gridLayout.addWidget(self.label_extinction, 11, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 10, 0, 1, 5)
        self.le_swing = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_swing.sizePolicy().hasHeightForWidth())
        self.le_swing.setSizePolicy(sizePolicy)
        self.le_swing.setObjectName("le_swing")
        self.gridLayout.addWidget(self.le_swing, 2, 3, 1, 2)
        self.label_wavelength = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_wavelength.setObjectName("label_wavelength")
        self.gridLayout.addWidget(self.label_wavelength, 3, 0, 1, 2)
        self.checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 5, 0, 1, 3)
        self.label_progress = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_progress.setObjectName("label_progress")
        self.gridLayout.addWidget(self.label_progress, 9, 2, 1, 2)
        self.le_extinction = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_extinction.sizePolicy().hasHeightForWidth())
        self.le_extinction.setSizePolicy(sizePolicy)
        self.le_extinction.setReadOnly(True)
        self.le_extinction.setObjectName("le_extinction")
        self.gridLayout.addWidget(self.le_extinction, 11, 1, 1, 4)
        self.label_dir = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_dir.setObjectName("label_dir")
        self.gridLayout.addWidget(self.label_dir, 1, 0, 1, 1)
        self.label_inten_plot_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_inten_plot_2.setObjectName("label_inten_plot_2")
        self.gridLayout.addWidget(self.label_inten_plot_2, 16, 0, 1, 1)
        self.label_calibration_params_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_calibration_params_4.setFont(font)
        self.label_calibration_params_4.setObjectName("label_calibration_params_4")
        self.gridLayout.addWidget(self.label_calibration_params_4, 6, 0, 1, 4)
        self.label_inten_plot = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_inten_plot.setObjectName("label_inten_plot")
        self.gridLayout.addWidget(self.label_inten_plot, 14, 0, 1, 1)
        self.cb_calibration_mode = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.cb_calibration_mode.setObjectName("cb_calibration_mode")
        self.cb_calibration_mode.addItem("")
        self.cb_calibration_mode.addItem("")
        self.cb_calibration_mode.addItem("")
        self.gridLayout.addWidget(self.cb_calibration_mode, 4, 3, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.le_wavelength.setText(_translate("Form", "532"))
        self.label_scheme.setText(_translate("Form", "Illumination Scheme"))
        self.label_calibration_params.setText(_translate("Form", "Calibration Parameters"))
        self.qbutton_calibrate_lc.setText(_translate("Form", "Calibrate LC"))
        self.label_calibration_params_5.setText(_translate("Form", "Calibration Feedback"))
        self.label_swing.setText(_translate("Form", "Swing"))
        self.pushButton.setText(_translate("Form", "Browse"))
        self.lineEdit.setText(_translate("Form", "/path/"))
        self.label_extinction.setText(_translate("Form", "Extinction"))
        self.le_swing.setText(_translate("Form", "0.03"))
        self.label_wavelength.setText(_translate("Form", "Wavelength"))
        self.checkBox.setText(_translate("Form", "Use Cropped ROI"))
        self.label_progress.setText(_translate("Form", "Progress"))
        self.label_dir.setText(_translate("Form", "Directory"))
        self.label_inten_plot_2.setText(_translate("Form", "Log"))
        self.label_calibration_params_4.setText(_translate("Form", "Run Calibration"))
        self.label_inten_plot.setText(_translate("Form", "Intensity Plot"))
        self.cb_calibration_mode.setItemText(0, _translate("Form", "Full"))
        self.cb_calibration_mode.setItemText(1, _translate("Form", "Coarse"))
        self.cb_calibration_mode.setItemText(2, _translate("Form", "Fine"))

