# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/cameron.foltz/recOrder/recOrder/plugin/qtdesigner/recOrder_calibration_v4.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(442, 978)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 416, 1101))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.calib_params = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.calib_params.setFont(font)
        self.calib_params.setObjectName("calib_params")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.calib_params)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_dir = QtWidgets.QLabel(self.calib_params)
        self.label_dir.setObjectName("label_dir")
        self.gridLayout_2.addWidget(self.label_dir, 0, 0, 1, 1)
        self.label_swing = QtWidgets.QLabel(self.calib_params)
        self.label_swing.setObjectName("label_swing")
        self.gridLayout_2.addWidget(self.label_swing, 2, 0, 1, 1)
        self.label_wavelength = QtWidgets.QLabel(self.calib_params)
        self.label_wavelength.setObjectName("label_wavelength")
        self.gridLayout_2.addWidget(self.label_wavelength, 3, 0, 1, 1)
        self.label_scheme = QtWidgets.QLabel(self.calib_params)
        self.label_scheme.setObjectName("label_scheme")
        self.gridLayout_2.addWidget(self.label_scheme, 4, 0, 1, 1)
        self.chb_use_roi = QtWidgets.QCheckBox(self.calib_params)
        self.chb_use_roi.setObjectName("chb_use_roi")
        self.gridLayout_2.addWidget(self.chb_use_roi, 5, 0, 1, 2)
        self.le_wavelength = QtWidgets.QLineEdit(self.calib_params)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.le_wavelength.setFont(font)
        self.le_wavelength.setObjectName("le_wavelength")
        self.gridLayout_2.addWidget(self.le_wavelength, 3, 1, 1, 1)
        self.le_directory = QtWidgets.QLineEdit(self.calib_params)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.le_directory.setFont(font)
        self.le_directory.setObjectName("le_directory")
        self.gridLayout_2.addWidget(self.le_directory, 0, 1, 1, 1)
        self.qbutton_browse = QtWidgets.QPushButton(self.calib_params)
        self.qbutton_browse.setAutoFillBackground(False)
        self.qbutton_browse.setCheckable(False)
        self.qbutton_browse.setDefault(False)
        self.qbutton_browse.setObjectName("qbutton_browse")
        self.gridLayout_2.addWidget(self.qbutton_browse, 0, 2, 1, 1)
        self.le_swing = QtWidgets.QLineEdit(self.calib_params)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.le_swing.setFont(font)
        self.le_swing.setObjectName("le_swing")
        self.gridLayout_2.addWidget(self.le_swing, 2, 1, 1, 1)
        self.cb_calib_scheme = QtWidgets.QComboBox(self.calib_params)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cb_calib_scheme.setFont(font)
        self.cb_calib_scheme.setObjectName("cb_calib_scheme")
        self.cb_calib_scheme.addItem("")
        self.cb_calib_scheme.addItem("")
        self.gridLayout_2.addWidget(self.cb_calib_scheme, 4, 1, 1, 2)
        self.gridLayout.addWidget(self.calib_params, 3, 0, 1, 1)
        self.calib_feedback = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.calib_feedback.setFont(font)
        self.calib_feedback.setObjectName("calib_feedback")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.calib_feedback)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_inten_plot = QtWidgets.QLabel(self.calib_feedback)
        self.label_inten_plot.setObjectName("label_inten_plot")
        self.verticalLayout.addWidget(self.label_inten_plot)
        self.plot_widget = PlotWidget(self.calib_feedback)
        self.plot_widget.setMinimumSize(QtCore.QSize(0, 250))
        self.plot_widget.setObjectName("plot_widget")
        self.verticalLayout.addWidget(self.plot_widget)
        self.label_log = QtWidgets.QLabel(self.calib_feedback)
        self.label_log.setObjectName("label_log")
        self.verticalLayout.addWidget(self.label_log)
        self.te_log = QtWidgets.QPlainTextEdit(self.calib_feedback)
        self.te_log.setMinimumSize(QtCore.QSize(0, 150))
        self.te_log.setLineWidth(1)
        self.te_log.setReadOnly(True)
        self.te_log.setBackgroundVisible(True)
        self.te_log.setObjectName("te_log")
        self.verticalLayout.addWidget(self.te_log)
        self.gridLayout.addWidget(self.calib_feedback, 6, 0, 1, 1)
        self.capture_background = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.capture_background.setFont(font)
        self.capture_background.setObjectName("capture_background")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.capture_background)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_bg_folder = QtWidgets.QLabel(self.capture_background)
        self.label_bg_folder.setObjectName("label_bg_folder")
        self.gridLayout_3.addWidget(self.label_bg_folder, 0, 0, 1, 1)
        self.qbutton_capture_bg = QtWidgets.QPushButton(self.capture_background)
        self.qbutton_capture_bg.setObjectName("qbutton_capture_bg")
        self.gridLayout_3.addWidget(self.qbutton_capture_bg, 2, 0, 1, 2)
        self.le_bg_folder = QtWidgets.QLineEdit(self.capture_background)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.le_bg_folder.setFont(font)
        self.le_bg_folder.setObjectName("le_bg_folder")
        self.gridLayout_3.addWidget(self.le_bg_folder, 0, 1, 1, 1)
        self.le_n_avg = QtWidgets.QLineEdit(self.capture_background)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.le_n_avg.setFont(font)
        self.le_n_avg.setObjectName("le_n_avg")
        self.gridLayout_3.addWidget(self.le_n_avg, 1, 1, 1, 1)
        self.label_n_avg = QtWidgets.QLabel(self.capture_background)
        self.label_n_avg.setObjectName("label_n_avg")
        self.gridLayout_3.addWidget(self.label_n_avg, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.capture_background, 5, 0, 1, 1)
        self.run_calib = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.run_calib.setFont(font)
        self.run_calib.setObjectName("run_calib")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.run_calib)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.qbutton_calibrate = QtWidgets.QPushButton(self.run_calib)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qbutton_calibrate.sizePolicy().hasHeightForWidth())
        self.qbutton_calibrate.setSizePolicy(sizePolicy)
        self.qbutton_calibrate.setAutoDefault(False)
        self.qbutton_calibrate.setObjectName("qbutton_calibrate")
        self.verticalLayout_2.addWidget(self.qbutton_calibrate)
        self.label_progress = QtWidgets.QLabel(self.run_calib)
        self.label_progress.setObjectName("label_progress")
        self.verticalLayout_2.addWidget(self.label_progress)
        self.progress_bar = QtWidgets.QProgressBar(self.run_calib)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.verticalLayout_2.addWidget(self.progress_bar)
        self.label_extinction = QtWidgets.QLabel(self.run_calib)
        self.label_extinction.setObjectName("label_extinction")
        self.verticalLayout_2.addWidget(self.label_extinction)
        self.le_extinction = QtWidgets.QLineEdit(self.run_calib)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_extinction.sizePolicy().hasHeightForWidth())
        self.le_extinction.setSizePolicy(sizePolicy)
        self.le_extinction.setReadOnly(True)
        self.le_extinction.setObjectName("le_extinction")
        self.verticalLayout_2.addWidget(self.le_extinction)
        self.gridLayout.addWidget(self.run_calib, 4, 0, 1, 1)
        self.connect_to_micromanager = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.connect_to_micromanager.setFont(font)
        self.connect_to_micromanager.setObjectName("connect_to_micromanager")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.connect_to_micromanager)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.qbutton_mm_connect = QtWidgets.QPushButton(self.connect_to_micromanager)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.qbutton_mm_connect.setFont(font)
        self.qbutton_mm_connect.setObjectName("qbutton_mm_connect")
        self.horizontalLayout.addWidget(self.qbutton_mm_connect)
        self.le_mm_status = QtWidgets.QLineEdit(self.connect_to_micromanager)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.le_mm_status.setFont(font)
        self.le_mm_status.setObjectName("le_mm_status")
        self.horizontalLayout.addWidget(self.le_mm_status)
        self.gridLayout.addWidget(self.connect_to_micromanager, 0, 0, 3, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.calib_params.setTitle(_translate("Form", "Calibration Parameters"))
        self.label_dir.setText(_translate("Form", "Directory"))
        self.label_swing.setText(_translate("Form", "Swing"))
        self.label_wavelength.setText(_translate("Form", "Wavelength"))
        self.label_scheme.setText(_translate("Form", "Illumination Scheme"))
        self.chb_use_roi.setText(_translate("Form", "Use Cropped ROI"))
        self.le_wavelength.setText(_translate("Form", "532"))
        self.le_directory.setText(_translate("Form", "/path/to/directory"))
        self.qbutton_browse.setText(_translate("Form", "Browse"))
        self.le_swing.setText(_translate("Form", "0.1"))
        self.cb_calib_scheme.setItemText(0, _translate("Form", "4-State (Ext, 0, 60, 120)"))
        self.cb_calib_scheme.setItemText(1, _translate("Form", "5-State (Ext, 0, 45, 90, 135)"))
        self.calib_feedback.setTitle(_translate("Form", "Calibration Feedback"))
        self.label_inten_plot.setText(_translate("Form", "Intensity Plot"))
        self.label_log.setText(_translate("Form", "Log"))
        self.capture_background.setTitle(_translate("Form", "Capture Background"))
        self.label_bg_folder.setText(_translate("Form", "Background Folder Name"))
        self.qbutton_capture_bg.setText(_translate("Form", "Capture Background"))
        self.le_bg_folder.setText(_translate("Form", "BG"))
        self.le_n_avg.setText(_translate("Form", "20"))
        self.label_n_avg.setText(_translate("Form", "Number of Images to Average"))
        self.run_calib.setTitle(_translate("Form", "Run Calibration"))
        self.qbutton_calibrate.setText(_translate("Form", "Calibrate LC"))
        self.label_progress.setText(_translate("Form", "Progress"))
        self.label_extinction.setText(_translate("Form", "Extinction"))
        self.connect_to_micromanager.setTitle(_translate("Form", "Connect to Micromanager"))
        self.qbutton_mm_connect.setText(_translate("Form", "Connect to MM"))
        self.le_mm_status.setText(_translate("Form", "Success!"))

from pyqtgraph import PlotWidget
