# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/cameron.foltz/recOrder/recOrder/plugin/qtdesigner/recOrder_calibration_scroll.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ScrollArea(object):
    def setupUi(self, ScrollArea):
        ScrollArea.setObjectName("ScrollArea")
        ScrollArea.resize(486, 630)
        # ScrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 484, 628))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox.setGeometry(QtCore.QRect(10, 160, 141, 20))
        self.checkBox.setObjectName("checkBox")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setGeometry(QtCore.QRect(380, 40, 87, 21))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setCheckable(False)
        self.pushButton.setDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.cb_calibration_mode = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.cb_calibration_mode.setGeometry(QtCore.QRect(160, 125, 187, 31))
        self.cb_calibration_mode.setObjectName("cb_calibration_mode")
        self.cb_calibration_mode.addItem("")
        self.cb_calibration_mode.addItem("")
        self.cb_calibration_mode.addItem("")
        self.label_calibration_params = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_calibration_params.setGeometry(QtCore.QRect(10, 10, 171, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_calibration_params.setFont(font)
        self.label_calibration_params.setObjectName("label_calibration_params")
        self.label_extinction = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_extinction.setGeometry(QtCore.QRect(10, 420, 60, 21))
        self.label_extinction.setObjectName("label_extinction")
        self.label_scheme = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_scheme.setGeometry(QtCore.QRect(10, 130, 131, 16))
        self.label_scheme.setObjectName("label_scheme")
        self.label_wavelength = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_wavelength.setGeometry(QtCore.QRect(10, 100, 91, 21))
        self.label_wavelength.setObjectName("label_wavelength")
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit.setGeometry(QtCore.QRect(160, 40, 211, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_swing = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_swing.setGeometry(QtCore.QRect(10, 70, 73, 21))
        self.label_swing.setObjectName("label_swing")
        self.qbutton_calibrate_lc = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.qbutton_calibrate_lc.setGeometry(QtCore.QRect(10, 260, 311, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qbutton_calibrate_lc.sizePolicy().hasHeightForWidth())
        self.qbutton_calibrate_lc.setSizePolicy(sizePolicy)
        self.qbutton_calibrate_lc.setAutoDefault(False)
        self.qbutton_calibrate_lc.setObjectName("qbutton_calibrate_lc")
        self.progressBar = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar.setGeometry(QtCore.QRect(10, 370, 291, 21))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_calibration_params_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_calibration_params_2.setGeometry(QtCore.QRect(270, 250, 161, 21))
        self.label_calibration_params_2.setText("")
        self.label_calibration_params_2.setObjectName("label_calibration_params_2")
        self.le_swing = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.le_swing.setGeometry(QtCore.QRect(160, 70, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_swing.sizePolicy().hasHeightForWidth())
        self.le_swing.setSizePolicy(sizePolicy)
        self.le_swing.setObjectName("le_swing")
        self.label_calibration_params_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_calibration_params_5.setGeometry(QtCore.QRect(10, 480, 171, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_calibration_params_5.setFont(font)
        self.label_calibration_params_5.setObjectName("label_calibration_params_5")
        self.label_inten_plot_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_inten_plot_2.setGeometry(QtCore.QRect(120, 750, 31, 16))
        self.label_inten_plot_2.setObjectName("label_inten_plot_2")
        self.plot_window = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.plot_window.setGeometry(QtCore.QRect(10, 530, 256, 192))
        self.plot_window.setObjectName("plot_window")
        self.label_inten_plot = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_inten_plot.setGeometry(QtCore.QRect(100, 510, 111, 16))
        self.label_inten_plot.setObjectName("label_inten_plot")
        self.label_dir = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_dir.setGeometry(QtCore.QRect(10, 40, 56, 16))
        self.label_dir.setObjectName("label_dir")
        self.label_calibration_params_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_calibration_params_4.setGeometry(QtCore.QRect(10, 230, 171, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_calibration_params_4.setFont(font)
        self.label_calibration_params_4.setObjectName("label_calibration_params_4")
        self.le_wavelength = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.le_wavelength.setGeometry(QtCore.QRect(160, 100, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_wavelength.sizePolicy().hasHeightForWidth())
        self.le_wavelength.setSizePolicy(sizePolicy)
        self.le_wavelength.setObjectName("le_wavelength")
        self.label_progress = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_progress.setGeometry(QtCore.QRect(130, 340, 60, 21))
        self.label_progress.setObjectName("label_progress")
        self.le_extinction = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.le_extinction.setGeometry(QtCore.QRect(80, 420, 221, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_extinction.sizePolicy().hasHeightForWidth())
        self.le_extinction.setSizePolicy(sizePolicy)
        self.le_extinction.setReadOnly(True)
        self.le_extinction.setObjectName("le_extinction")
        self.plot_window_2 = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.plot_window_2.setGeometry(QtCore.QRect(10, 770, 256, 131))
        self.plot_window_2.setObjectName("plot_window_2")
        ScrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(ScrollArea)
        QtCore.QMetaObject.connectSlotsByName(ScrollArea)

    def retranslateUi(self, ScrollArea):
        _translate = QtCore.QCoreApplication.translate
        ScrollArea.setWindowTitle(_translate("ScrollArea", "ScrollArea"))
        self.checkBox.setText(_translate("ScrollArea", "Use Cropped ROI"))
        self.pushButton.setText(_translate("ScrollArea", "Browse"))
        self.cb_calibration_mode.setItemText(0, _translate("ScrollArea", "Full"))
        self.cb_calibration_mode.setItemText(1, _translate("ScrollArea", "Coarse"))
        self.cb_calibration_mode.setItemText(2, _translate("ScrollArea", "Fine"))
        self.label_calibration_params.setText(_translate("ScrollArea", "Calibration Parameters"))
        self.label_extinction.setText(_translate("ScrollArea", "Extinction"))
        self.label_scheme.setText(_translate("ScrollArea", "Illumination Scheme"))
        self.label_wavelength.setText(_translate("ScrollArea", "Wavelength"))
        self.lineEdit.setText(_translate("ScrollArea", "/path/"))
        self.label_swing.setText(_translate("ScrollArea", "Swing"))
        self.qbutton_calibrate_lc.setText(_translate("ScrollArea", "Calibrate LC"))
        self.le_swing.setText(_translate("ScrollArea", "0.03"))
        self.label_calibration_params_5.setText(_translate("ScrollArea", "Calibration Feedback"))
        self.label_inten_plot_2.setText(_translate("ScrollArea", "Log"))
        self.label_inten_plot.setText(_translate("ScrollArea", "Intensity Plot"))
        self.label_dir.setText(_translate("ScrollArea", "Directory"))
        self.label_calibration_params_4.setText(_translate("ScrollArea", "Run Calibration"))
        self.le_wavelength.setText(_translate("ScrollArea", "532"))
        self.label_progress.setText(_translate("ScrollArea", "Progress"))

