# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/cameron.foltz/recOrder/recOrder/plugin/qtdesigner/recOrder_calibration_v3.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(563, 925)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(20, 10, 541, 891))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 539, 889))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setGeometry(QtCore.QRect(12, 12, 495, 191))
        self.widget.setObjectName("widget")
        self.label_swing_2 = QtWidgets.QLabel(self.widget)
        self.label_swing_2.setGeometry(QtCore.QRect(10, 70, 73, 21))
        self.label_swing_2.setObjectName("label_swing_2")
        self.le_swing_2 = QtWidgets.QLineEdit(self.widget)
        self.le_swing_2.setGeometry(QtCore.QRect(160, 70, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_swing_2.sizePolicy().hasHeightForWidth())
        self.le_swing_2.setSizePolicy(sizePolicy)
        self.le_swing_2.setObjectName("le_swing_2")
        self.le_wavelength_2 = QtWidgets.QLineEdit(self.widget)
        self.le_wavelength_2.setGeometry(QtCore.QRect(160, 100, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_wavelength_2.sizePolicy().hasHeightForWidth())
        self.le_wavelength_2.setSizePolicy(sizePolicy)
        self.le_wavelength_2.setObjectName("le_wavelength_2")
        self.cb_calibration_mode_2 = QtWidgets.QComboBox(self.widget)
        self.cb_calibration_mode_2.setGeometry(QtCore.QRect(160, 125, 187, 31))
        self.cb_calibration_mode_2.setObjectName("cb_calibration_mode_2")
        self.cb_calibration_mode_2.addItem("")
        self.cb_calibration_mode_2.addItem("")
        self.cb_calibration_mode_2.addItem("")
        self.label_wavelength_2 = QtWidgets.QLabel(self.widget)
        self.label_wavelength_2.setGeometry(QtCore.QRect(10, 100, 91, 21))
        self.label_wavelength_2.setObjectName("label_wavelength_2")
        self.label_scheme_2 = QtWidgets.QLabel(self.widget)
        self.label_scheme_2.setGeometry(QtCore.QRect(10, 130, 131, 16))
        self.label_scheme_2.setObjectName("label_scheme_2")
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 160, 141, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 40, 87, 21))
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setDefault(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 40, 211, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_dir_2 = QtWidgets.QLabel(self.widget)
        self.label_dir_2.setGeometry(QtCore.QRect(10, 40, 71, 16))
        self.label_dir_2.setObjectName("label_dir_2")
        self.label_calibration_params = QtWidgets.QLabel(self.widget)
        self.label_calibration_params.setGeometry(QtCore.QRect(10, 0, 256, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_calibration_params.setFont(font)
        self.label_calibration_params.setObjectName("label_calibration_params")
        self.widget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_2.setGeometry(QtCore.QRect(12, 210, 495, 211))
        self.widget_2.setObjectName("widget_2")
        self.le_extinction_2 = QtWidgets.QLineEdit(self.widget_2)
        self.le_extinction_2.setGeometry(QtCore.QRect(90, 170, 231, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_extinction_2.sizePolicy().hasHeightForWidth())
        self.le_extinction_2.setSizePolicy(sizePolicy)
        self.le_extinction_2.setReadOnly(True)
        self.le_extinction_2.setObjectName("le_extinction_2")
        self.label_extinction_2 = QtWidgets.QLabel(self.widget_2)
        self.label_extinction_2.setGeometry(QtCore.QRect(20, 170, 71, 21))
        self.label_extinction_2.setObjectName("label_extinction_2")
        self.label_progress_2 = QtWidgets.QLabel(self.widget_2)
        self.label_progress_2.setGeometry(QtCore.QRect(140, 90, 61, 21))
        self.label_progress_2.setObjectName("label_progress_2")
        self.qbutton_calibrate_lc_2 = QtWidgets.QPushButton(self.widget_2)
        self.qbutton_calibrate_lc_2.setGeometry(QtCore.QRect(10, 30, 311, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qbutton_calibrate_lc_2.sizePolicy().hasHeightForWidth())
        self.qbutton_calibrate_lc_2.setSizePolicy(sizePolicy)
        self.qbutton_calibrate_lc_2.setAutoDefault(False)
        self.qbutton_calibrate_lc_2.setObjectName("qbutton_calibrate_lc_2")
        self.progressBar_2 = QtWidgets.QProgressBar(self.widget_2)
        self.progressBar_2.setGeometry(QtCore.QRect(20, 120, 301, 21))
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.label_calibration_params_6 = QtWidgets.QLabel(self.widget_2)
        self.label_calibration_params_6.setGeometry(QtCore.QRect(20, 10, 256, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_calibration_params_6.setFont(font)
        self.label_calibration_params_6.setObjectName("label_calibration_params_6")
        self.widget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_3.setGeometry(QtCore.QRect(12, 430, 495, 451))
        self.widget_3.setObjectName("widget_3")
        self.label_inten_plot_3 = QtWidgets.QLabel(self.widget_3)
        self.label_inten_plot_3.setGeometry(QtCore.QRect(130, 260, 31, 16))
        self.label_inten_plot_3.setObjectName("label_inten_plot_3")
        self.plot_window_3 = QtWidgets.QGraphicsView(self.widget_3)
        self.plot_window_3.setGeometry(QtCore.QRect(20, 60, 256, 192))
        self.plot_window_3.setObjectName("plot_window_3")
        self.plot_window_4 = QtWidgets.QGraphicsView(self.widget_3)
        self.plot_window_4.setGeometry(QtCore.QRect(20, 280, 256, 131))
        self.plot_window_4.setObjectName("plot_window_4")
        self.label_inten_plot_4 = QtWidgets.QLabel(self.widget_3)
        self.label_inten_plot_4.setGeometry(QtCore.QRect(110, 40, 111, 16))
        self.label_inten_plot_4.setObjectName("label_inten_plot_4")
        self.label_calibration_params_7 = QtWidgets.QLabel(self.widget_3)
        self.label_calibration_params_7.setGeometry(QtCore.QRect(20, 10, 256, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_calibration_params_7.setFont(font)
        self.label_calibration_params_7.setObjectName("label_calibration_params_7")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_swing_2.setText(_translate("Form", "Swing"))
        self.le_swing_2.setText(_translate("Form", "0.03"))
        self.le_wavelength_2.setText(_translate("Form", "532"))
        self.cb_calibration_mode_2.setItemText(0, _translate("Form", "Full"))
        self.cb_calibration_mode_2.setItemText(1, _translate("Form", "Coarse"))
        self.cb_calibration_mode_2.setItemText(2, _translate("Form", "Fine"))
        self.label_wavelength_2.setText(_translate("Form", "Wavelength"))
        self.label_scheme_2.setText(_translate("Form", "Illumination Scheme"))
        self.checkBox_2.setText(_translate("Form", "Use Cropped ROI"))
        self.pushButton_2.setText(_translate("Form", "Browse"))
        self.lineEdit_2.setText(_translate("Form", "/path/"))
        self.label_dir_2.setText(_translate("Form", "Directory"))
        self.label_calibration_params.setText(_translate("Form", "Calibration Parameters"))
        self.label_extinction_2.setText(_translate("Form", "Extinction"))
        self.label_progress_2.setText(_translate("Form", "Progress"))
        self.qbutton_calibrate_lc_2.setText(_translate("Form", "Calibrate LC"))
        self.label_calibration_params_6.setText(_translate("Form", "Run Calibration"))
        self.label_inten_plot_3.setText(_translate("Form", "Log"))
        self.label_inten_plot_4.setText(_translate("Form", "Intensity Plot"))
        self.label_calibration_params_7.setText(_translate("Form", "Calibration Feedback"))

